version: "3"
services:
  golang:
    container_name: api_echo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    tty:  true
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - 1234:1234
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres
      DB_PORT: 5432
      DB_HOST: postgres

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/posrgresql/data

volumes:
  db_data: {}